export const listReligion = [
  'Bửu Sơn Kỳ Hương',
  'Cao đài',
  'Công giáo',
  'Cơ đốc Phục lâm',
  'Hồi giáo',
  'Minh Sư đạo',
  'Mặc môn',
  'Phật Giáo',
  'Phật giáo Hiếu Nghĩa Tà Lơn',
  'Phật giáo Hòa Hảo',
  'Phật giáo Tứ Ân Hiếu nghĩa',
  'Tin lành',
  "Tôn giáo Baha'l",
  'Tịnh độ cư sỹ Phật hội',
  'Không',
];

export const listEthnic = [
  'Ba na',
  'Bru-Vân kiều',
  'Brâu',
  'Bố Y',
  'Chu-ru',
  'Chăm',
  'Chơ-ro',
  'Chứt',
  'Co',
  'Cơ-ho',
  'Cơ-tu',
  'Cống',
  'Cờ lao',
  'Dao',
  'Gia-rai',
  'Giáy',
  'Gié-triêng',
  'Hoa',
  'Hrê',
  'Hà nhì',
  'Khmer',
  'Kháng',
  'Khơ mú',
  'Kinh',
  'La Chí',
  'La ha',
  'La hủ',
  'Lào',
  'Lô lô',
  'Lự',
  "M'Nông",
  'Mông',
  'Mường',
  'Mạ',
  'Mảng',
  'Ngái',
  'Nùng',
  'Phù lá',
  'Pu péo',
  'Pà thẻn',
  'Ra-glai',
  'Rơ-măm',
  'Si la',
  'Sán Chay',
  'Sán dìu',
  'Thái',
  'Thổ',
  'Tà-ôi',
  'Tày',
  'Xinh-mun',
  'Xtiêng',
  'Xơ-đăng',
  'Ê đê',
  'Ơ-đu',
];

export const listLevel = [
  'Mù chữ',
  'Tiểu học',
  'Trung học cơ sở',
  'Trung học phổ thông',
  'Cao đẳng',
  'Đại học và trên đại học',
];

export const listCareer = [
  'Biên dịch viên',
  'Biên kịch',
  'Biên tập viên',
  'Biên đạo múa',
  'Blogger',
  'Bác sỹ chuyên khoa',
  'Bác sỹ đa khoa',
  'Bán buôn, bán lẻ',
  'Bán hàng và tiếp thị',
  'Bảo vệ tòa nhà',
  'Bồi bàn',
  'Bộ đội',
  'Ca sĩ',
  'Chuyên gia',
  'Chuyên gia về công nghệ thông tin',
  'Chuyên gia về giáo dục',
  'Chuyên gia về tôn giáo',
  'Chủ cửa hàng',
  'Chủ hiệu cầm đồ',
  'Content creator',
  'Các lực lượng vũ trang khác',
  'Còn nhỏ',
  'Công an',
  'Công chứng viên',
  'Công nhân',
  'Cơ yếu',
  'Designer',
  'Diễn viên',
  'Dược sĩ',
  'Dịch vụ kinh doanh',
  'Dịch vụ lưu trú và ăn uống',
  'Dịch vụ vận tải',
  'Điều dưỡng',
  'Đại lý thu mua',
  'Đạo diễn',
  'Đầu bếp',
  'Gamer',
  'Giám sát viên',
  'Giáo viên',
  'Giảng viên',
  'Huấn luyện viên',
  'Hướng dẫn viên du lịch',
  'Họa sĩ',
  'Hộ sinh',
  'Kiểm lâm',
  'Kiểm lâm',
  'Kiểm soát không lưu',
  'Kiểm sát viên',
  'Kiểm toán',
  'Kế toán',
  'Kỹ sư',
  'Kỹ thuật viên',
  'Lao công',
  'Lao động chăn nuôi',
  'Lao động công nghiệp',
  'Lao động lâm nghiệp',
  'Lao động thủy sản',
  'Lao động trồng trọt',
  'Luật sư',
  'Lái xe',
  'Lái xe',
  'Lái xe công nghệ',
  'Lãnh đạo các cơ quan nhà nước cấp Trung ương',
  'Lãnh đạo các cơ quan nhà nước cấp quận/huyện/thành phố/thị xã',
  'Lãnh đạo các cơ quan nhà nước cấp thôn/xóm/khu phố',
  'Lãnh đạo các cơ quan nhà nước cấp tỉnh/thành phố',
  'Lãnh đạo các cơ quan nhà nước cấp xã/phường/thị trấn',
  'Lãnh đạo các tổ chức',
  'Lập trình viên',
  'Lực lượng khác trong công an',
  'Lực lượng khác trong quân đội',
  'Nghệ sĩ',
  'Người bán hàng trên đường phố và chợ',
  'Người chiêm tương, tướng số và tâm linh',
  'Người cho vay tiền',
  'Người khuân vác',
  'Người trông đỗ bãi xe',
  'Người đưa thư',
  'Nhiếp ảnh gia',
  'Nhà báo',
  'Nhà chuyên môn về luật',
  'Nhà chuyên môn về y tế',
  'Nhà khoa học',
  'Nhà khoa học máy tính',
  'Nhà khảo sát',
  'Nhà kinh tế học',
  'Nhà ngoại giao',
  'Nhà ngôn ngữ học',
  'Nhà phân tích kinh tế',
  'Nhà quản lý kinh tế',
  'Nhà quản trị cơ sở dữ liệu',
  'Nhà quản trị hệ thống',
  'Nhà thiên văn học',
  'Nhà thiết kế',
  'Nhà toán học',
  'Nhà tâm lý học',
  'Nhà tư vấn tài chính',
  'Nhà văn',
  'Nhà vật lý học',
  'Nhà điêu khắc',
  'Nhân viên bán hàng trong cửa hàng',
  'Nhân viên các cơ quan nhà nước cấp nhà nước',
  'Nhân viên các cơ quan nhà nước cấp quận/huyện/thành phố/thị xã',
  'Nhân viên các cơ quan nhà nước cấp thôn/xóm/khu phố',
  'Nhân viên các cơ quan nhà nước cấp tỉnh/thành phố',
  'Nhân viên các cơ quan nhà nước cấp xã/phường/thị trấn',
  'Nhân viên công tác xã hội',
  'Nhân viên dịch vụ khách hàng',
  'Nhân viên giao dịch ngân hàng',
  'Nhân viên nhập liệu',
  'Nhân viên pha chế',
  'Nhân viên thu ngân',
  'Nhân viên tổ chức sự kiện',
  'Nhân viên/Đại lý mua hàng',
  'Nhạc công',
  'Nhạc sỹ',
  'Nhạc trưởng',
  'Nội trợ',
  'Phi công',
  'Phiên dịch viên',
  'Phát thanh viên',
  'Phụ xe',
  'Shipper',
  'Streamer',
  'Thanh tra nghề nghiệp',
  'Thám tử',
  'Thư ký',
  'Thất nghiệp',
  'Thẩm phán',
  'Thẩm định viên',
  'Thợ giết mổ',
  'Thợ làm bánh',
  'Thợ làm đầu',
  'Thợ làm đẹp',
  'Thợ làm đồ các loại',
  'Thợ lắp đặt',
  'Thợ rửa xe',
  'Thợ sửa chữa',
  'Thợ thủ công',
  'Thợ vận hành, lắp ráp',
  'Thợ xây dựng',
  'Thủ quỹ',
  'Thủy thủ',
  'Tiếp viên hàng không',
  'Vũ công',
  'Vận động viên',
  'Xây dựng',
  'Y tá',
  'Youtuber',

  'Khác',
];
